Webpack
aBekar145/frontend-lab pull request #1
Opened 2021-08-31 15:42 UTC by aBekar145

2021-09-02 10:46 UTC, nastystanevich requested changes
Overall well done!
There's one comment in the code. 
As well add a compression of the files (so it should create `.gzip`, `.br` files in the `dist` folder)

2021-09-02 10:46 UTC, nastystanevich commented on workflow/webpack/dist/index.html
> +<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><link href="https://
as rule files inside `dist` folder aren't pushed to repo (so add them to `gitignore`)

2021-09-02 15:58 UTC, aBekar145 commented on workflow/webpack/dist/index.html
> +<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><link href="https://
fixed

2021-09-03 08:02 UTC, nastystanevich approved these changes

2021-09-03 08:02 UTC, merged